### PR TITLE
Command-line params plus iteration

### PR DESCRIPTION
**Pull request by prathamjoshi**
Modified `run_cosmics.py` : Now accepts (and requires) command-line parameters for `readnoise`, `iter` and `sigclip`.
File names generated for the output now include the parameters used to distinguish them.

Added script `iter_cosmics.py` : Runs `run_cosmics.py` with different values for iterations (currently set at 0-10) , readnoise (currently 2.5-7.5), and sigclip (currently 0.5 - 6.0). Currently uses file `u2mi0102t_c0m.fits`

Both scripts have been tested.

I am going to go through these scripts again to make sure it is going to do what we want and then am gonna run it for the above settings (should be around 250 images) before I leave at 5. If you could take a look before then and provide comments on any changes if necessary then that would be great. If not will look at the images generated tomorrow morning and let you know and we can tweak params from there.

### CODE REVIEW

**Comment by acviana** [comment]
Ok, do you know why this is telling me there are merge conflicts?

**Comment by prathamjoshi** [comment]
mm don't see anything that is obvious. I mean my other branch (master) of MTPipeline still has the old `run_cosmics.py` but I would not thing that should be an issue as it is an individual pull request. Where is the merge conflict? How do I see it?

**Comment by acviana** [comment]
http://blog.michelemattioni.me/2013/01/29/what-do-i-do-when-my-pull-request-does-not-merge-automatically-in-master/

**Comment by prathamjoshi** [comment]
Tried that but not sure if it is helping. I get a 'Already up-to-date' when I try to merge my two branches.

**Comment by acviana** [comment]
Maybe you need to merge you branch back into master, pull master to rebase, and then push to master?

**Pull request merged**
