### PR TITLE
Added most of the docstrings to build_master_finders_table.py, what rema...

### PR DESCRIPTION
**Pull request by acviana**
...ins unupdated needs to be refactored. For Ticket #136. Local tests failing due to a missing dependency. Should still pass on Travis.

This is a refactor of the code as well as a complete reworking of all the major docstrings. There is still more work to be done but this can be done in the parent `update-master-finders` branch.

### CODE REVIEW

**Comment by acviana** [comment]
@walyssonBarbosa Once Travis has finished running these tests please review my changes and let me know your comments.

**Comment by acviana** [comment]
@walyssonBarbosa Please let me know when you have had a chance to look over my changes.

**Comment by acviana** [comment]
Just to confirm, I am going to merge this into your branch now. Is that OK?

**Comment by walyssonBarbosa** [comment]
Okay. Then I will have to do the changes again, right?

**Comment by acviana** [comment]
Yes, you can just copy them out and then copy them back in after the merge.

**Comment by walyssonBarbosa** [comment]
Ok.

**Pull request merged**
